from torchfed.modules.node.fedavg import DecentralizedFedAvgNode, CentralizedFedAvgServer, CentralizedFedAvgClient,CompressorDecentralizedFedAvgNode
from torchfed.modules.node.defta import DeFTANode
from torchfed.modules.node.fedprox import CentralizedFedProxServer,CentralizedFedProxClient
